### PR TITLE
Support for FS22_Lenormand_12m

### PR DESCRIPTION
**Pull request by KingArthurLV**
Added support for Lenormand 12m trailer. Implemented also extenders configuration for future mod update by AgriDesignModding.

[FS22_Lenormand_12m](https://www.farming-simulator.com/mod.php?lang=en&country=us&mod_id=270383&title=fs2022)

### CODE REVIEW

**Comment by KingArthurLV** [comment]
Added quick fix for FS22_AmericanFlatbedPack. Forgot remove "useConfigName"

**Comment by ddewar** [comment]
Not sure if I'm missing something, but these configs look way too long?

image

**Comment by KingArthurLV** [comment]
My bad, fixed in last commit.

**Comment by ddewar** [comment]
image

Still seeing length issues when the folding parts are not included.

**Comment by ddewar** [comment]
> image
> 
> Still seeing length issues when the folding parts are not included.

Nevermind, its just bugging from the save game. We're good.

**Comment by ddewar** [comment]
Only thing I see is the folded/unfolded stuff doesn't seem to work for me. Was that working for you?

**Comment by KingArthurLV** [comment]
Okey, I think I made more confusion on this than necesary.
Basicaly support is added for updated version of this mod, which was sended by mod creator in PR #86

I guess better would be just add support for regular size loading area for both versions for now, until it is updated in Modhub.

In this note, actualy we would need some kind of tracker, to keep track updates and new releases of mods which are already in support list to retest and for possible new mods. I already have one big list, with mods which need to be support implemented.

**Pull request closed without merging**
