### PR TITLE
Update SupportedVehicles.xml

### PR DESCRIPTION
**Pull request by Vanquish081**
Support for ITRTwo:

https://www.farming-simulator.com/mod.php?&mod_id=259967

### CODE REVIEW

**Review by KingArthurLV — CHANGES_REQUESTED** [review]
Hi Vanquish081! I tested Your suggested support and I have some suggestions, which would look like that:

        <vehicleConfiguration configFileName="FS22_ITRTwo/ITRTwo.xml" selectedConfigs="1" modHubId="259967">
            <loadingArea offset="0.000 0.334 0.132" width="2.5" height="2.80" length="7.35"/>
            <options isBaleTrailer="true" enableRearLoading="true" enableSideLoading="true"/>
        </vehicleConfiguration>
        <vehicleConfiguration configFileName="FS22_ITRTwo/ITRTwo.xml" selectedConfigs="2" modHubId="259967">
            <loadingArea offset="0.000 0.5 0.15" width="2.35" height="2.3" length="7.1"/>
            <options isLogTrailer="true"/>
        </vehicleConfiguration>

Changes made:
- Removed showDebug="false" - it is only used for develepment purposes;
- Removed enableRearLoading="true" enableSideLoading="true" from log trailer, since it is redundant if isLogTrailer="true" declared.
- Adjusted ofset and xyz for both platforms to acomadate more items and log platform was too long.

**Comment by ddewar** [comment]
Small nitpick, leave the EnableSideLoading and rear options. @KingArthurLV they allow the auto loading triggers in that location. IsBaleTrailer allows auto pickup mode when driving. After checking with @loki79uk they have no connection.

**Comment by KingArthurLV** [comment]
Thanks @ddewar for clarification. I just checked all information I could and saw information that it is not necesarry. Maybe it is tru for isLogTrailer as well?

**Comment by ddewar** [comment]
Not sure. Could be a bug even. I will look into it more, but for now, no big deal to have both configured as it shows up in the documentation page.

**Comment by KingArthurLV** [comment]
That would be awesome if You can get that exact confirmation, so I could make some reworks on that and make some changes in that regards.

**Comment by loki79uk** [comment]
Which documentation are you looking at?  I can't see anything, but lets just say I'm not well known for keeping docs up to date :D

**Comment by KingArthurLV** [comment]
Basicaly all I could find is documentation in UnversalAutoload readme file on Github page and I looked trough previous comments and PR here.

**Comment by loki79uk** [comment]
>Basicaly all I could find is documentation in UnversalAutoload readme file on Github page
That should be the most up to date

> I just checked all information I could and saw information that it is not necesarry
Where did you see this?

**Comment by KingArthurLV** [comment]
I need to look trough all requests and PR to find it. But what @ddewar comented on one of suggested supports that if isLogTrailer is declared, than enableRearLoading="true" enableSideLoading="true" is not needed.

**Comment by KingArthurLV** [comment]
Found it it is in #54

**Comment by loki79uk** [comment]
Okay, I got confused and thought you were talking about bale trailers.  Yeah, for log trailers I think both are irrelevant because there is currently no manual loading possible for log trailers, and if/when I do implement it then it will probably be a new trigger position above the trailer.

**Comment by KingArthurLV** [comment]
Oh thanks God, I got it right. Thats what I done with Vanquish081 request - "cleaned" it up a bit.

**Comment by ddewar** [comment]
My bad @loki79uk and @KingArthurLV This is what I get for reading PRs while doing my real job. 👼 Forgive me please!

**Comment by KingArthurLV** [comment]
No worries :)

**Comment by Vanquish081** [comment]
@loki79uk is possible that this (this settings) cause the drop FPS? 🤔

**Comment by loki79uk** [comment]
> @loki79uk is possible that this (this settings) cause the drop FPS? 🤔

Yes, I think anything is possible.  Rear and side loading creates extra object triggers, so perfoming the collsions checks could affect the frame rate.

**Comment by Vanquish081** [comment]
@ddewar you can close and added the settings by @KingArthurLV  if you think that right.

**Comment by Vanquish081** [comment]
so... there is still a drop in fps @loki79uk

**Comment by KingArthurLV** [comment]
This PR has been implemented in PR #81 

PR closed.

**Pull request closed without merging**
